# Generated by Django 3.1 on 2020-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0003_auto_20200906_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='placetypes',
            field=models.ManyToManyField(to='tourit.PlaceType'),
        ),
    ]
