# Generated by Django 3.1 on 2020-09-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0008_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
