# Generated by Django 3.1 on 2020-10-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0011_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/images/profile1.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.RemoveField(
            model_name='place',
            name='placetypes',
        ),
        migrations.AddField(
            model_name='place',
            name='placetypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourit.placetype'),
        ),
    ]
