# Generated by Django 3.1 on 2020-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0012_auto_20201019_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='pic',
            field=models.ImageField(blank=True, default='/images/amusementpark.jpg', null=True, upload_to=''),
        ),
    ]
