# Generated by Django 3.1 on 2020-10-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0013_place_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pic',
            field=models.ImageField(blank=True, default='/images/amusementpark.jpeg', null=True, upload_to=''),
        ),
    ]
