# Generated by Django 3.1 on 2020-10-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0014_auto_20201020_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
