# Generated by Django 3.1 on 2020-10-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0015_auto_20201020_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
