# Generated by Django 3.1 on 2020-11-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0016_itinerary_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='slug',
        ),
        migrations.AddField(
            model_name='customer',
            name='place',
            field=models.ManyToManyField(blank=True, to='tourit.Place'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='ref_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='place',
        ),
        migrations.CreateModel(
            name='ItineraryPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wishlisted', models.BooleanField(default=False)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourit.place')),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='place',
            field=models.ManyToManyField(to='tourit.ItineraryPlace'),
        ),
    ]
