# Generated by Django 3.1 on 2020-11-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourit', '0018_auto_20201119_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='placetypepic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
